apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
{{ if eq .Values.service.type "ClusterIP" }}
  clusterIP: {{ .Values.service.clusterIP | default "None" | quote }}
{{ end }}
  ports:
    - port: {{ .Values.service.externalRpcPort }}
      targetPort: {{ .Values.service.internalRpcPort }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.metricsHttpPort }}
      targetPort: {{ .Values.service.metricsHttpPort }}
      protocol: TCP
      name: metrics-http
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-lb"
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
  - port: {{ .Values.service.externalRpcPort }}
    targetPort: {{ .Values.service.internalRpcPort }}
    name: grpclb
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
