replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/dispatcher
  tag: latest
  pullPolicy: Always
  pullSecrets: 
  - name: regcred

serviceAccount:
  name: default

service:
  loadBalancerIP: "35.223.13.150"
  ports:
    grpc: 5008
    metrics: 15008

resources:
  limits:
   cpu: 500m
   memory: 512Mi
  requests:
   cpu: 50m
   memory: 32Mi

autoscaler:
  minCount: 1
  maxCount: 5
  targets:
    targetCPUUtilizationPercentage: 70

config:
  ACCOUNTS_RPC_ADDR: "accounts.console.svc.cluster.local:5001"
  STREAMS_RPC_ADDR: "streams.console.svc.cluster.local:5102"
  EMITTER_RPC_ADDR: "emitter.console.svc.cluster.local:5003"
  VALIDATOR_RPC_ADDR: "validator.console.svc.cluster.local:5020"
  MINERS_RPC_ADDR: "miners.console.svc.cluster.local:5011"
  MEDIASERVER_RPC_ADDR: "mediaserver.console.svc.cluster.local:5090"

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "15008"
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-dispatcher"
  vault.hashicorp.com/agent-inject-secret-common: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/dev-videocoin-network/console-dev-videocoin-network/common/config"
  vault.hashicorp.com/agent-inject-secret-config: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/dev-videocoin-network/console-dev-videocoin-network/dispatcher/config"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/dev-videocoin-network/console-dev-videocoin-network/common/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/dev-videocoin-network/console-dev-videocoin-network/dispatcher/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
