replicasCount: 3
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/dispatcher
  tag: latest
  pullPolicy: Always

config: {}

service:
  type: ClusterIP
  externalRpcPort: 5008
  internalRpcPort: 5008

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

secrets:
  dbUri: ""
  mqUri: ""
  secret: ""
  sentryDsn: ""
